name: proxy_server
description: CORS proxy for chatapp
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  http: ^1.1.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
